package com.sparta.deliveryi.order.domain;

public enum OrderStatus {
    ORDER_REQUESTED, PAYMENT_COMPLETED, PAYMENT_FAILED, ORDER_ACCEPTED, ORDER_REJECTED,
    ORDER_CANCELED, READY_TO_SERVED, DELIVERING, ORDER_COMPLETED
}
